docs: improve developer and public project documentation
MESH-Research/CCR pull request #112
Opened 2021-01-25 18:56 UTC by wreality

2021-02-04 19:18 UTC, gmeben requested changes
Found some typos and grammatical fixes and suggested some improvements for readability and stylistic changes.

2021-02-04 19:18 UTC, gmeben commented on docs/contributing/testing.md
> +The [Majestic](https://github.com/Raathigesh/majestic) GUI for jest is a useful tool for running unit tests in a browser and watching code and tests for changes.  You can add the following config to
```suggestion
The [Majestic](https://github.com/Raathigesh/majestic) GUI for Jest is a useful tool for running unit tests in a browser and watching code and tests for changes.  You can add the following config to your `.lando.local.yml` file to enable a container for Majestic.
```

2021-02-05 03:10 UTC, wreality commented on docs/contributing/documentation.md
> +CCR's documentation (the site you're currently reading) is a [VuePress](https://vuepress.vuejs.org) site located in the `/docs` directory of the repo.  Our goal is to iterate the documentation as fea
This changes the meaning of what I was going for very slightly, but I'm cool with it.

2021-02-05 03:23 UTC, wreality commented on docs/contributing/README.md
> +appearance, race, religion, or sexual identity and orientation.
No newline is good with me.  I think a former version of the markdown lint had a line limit rule of 80 characters.  That was adjusted to 400, but this was probably written before the autoformatter was doing its thing in my VSCode.  Either way, agreed.

2021-02-05 03:24 UTC, wreality commented
Thanks much for looking it over in such detail.  With such a big chunk of text, I was sure there were bound to be errors and typos, try as I might.  Changes accepted, ready for approval.

2021-02-05 14:18 UTC, gmeben commented on docs/contributing/documentation.md
> +CCR's documentation (the site you're currently reading) is a [VuePress](https://vuepress.vuejs.org) site located in the `/docs` directory of the repo.  Our goal is to iterate the documentation as fea
Ah, then maybe to make it more clear it should've been written as, "Our goal is to iterate the documentation alongside features added to the application."

2021-02-05 16:05 UTC, gmeben approved these changes
Looking very good. Feel free to make further changes as you see fit.

2021-02-05 18:01 UTC, merged