feature: store login & logout data
MESH-Research/CCR pull request #113
Opened 2021-01-26 06:14 UTC by wreality

2021-01-26 06:20 UTC, wreality commented on client/src/components/mixins/appAuth.js
> +import { get } from "lodash";
```suggestion

```
Unused import

2021-01-26 06:21 UTC, wreality commented on client/src/components/mixins/appAuth.js
> +          errors: errors ?? [FAILURE_OTHER]
```suggestion
          errors: errors ?? ["FAILURE_OTHER"]
```

2021-01-26 06:23 UTC, wreality commented on client/src/layouts/MainLayout.vue
> +  methods: {}
```suggestion

```

2021-01-26 06:23 UTC, wreality commented on client/src/layouts/PublicLayout.vue
> +  methods: {}
```suggestion

```

2021-02-03 22:11 UTC, gmeben requested changes
While testing, I noticed that the email input validates the user input before the user focuses the following username input, which means it yells at me about my email not being valid before I've finished typing it. Not an ideal experience.

2021-02-03 22:31 UTC, wreality commented
Hmm. I thought I made it not do that. I'll try to replicate and fix it. Agree that's not an ideal experience. 

What browser in case it's not happening on chrome?

2021-02-03 22:40 UTC, wreality commented on client/src/layouts/MainLayout.vue
> +      <div class="drawer-header">Stuff To Do</div>
Good point. I'll add some content. At least links to profile and dashboard pages.

2021-02-04 06:26 UTC, wreality commented
@gmeben Fixed both of the issues you pointed out.  Let me know if there's anything else.

2021-02-04 15:16 UTC, gmeben commented
@wreality The email input validation issue appears to be fixed now as of testing in Chrome 88.0, Safari 14.0.2, and Firefox 85.0 on macOS 11.1.

2021-02-04 15:19 UTC, gmeben commented
@wreality Update: the email input on the register page is fixed but it looks like the email input on the login page has the same problem.

2021-02-04 15:33 UTC, gmeben requested changes
Confirmed Working

* Acceptance test registration and authentication
* Drawer flyout placeholder

Needs Fixing

* Email input at `/login` still validates before change

Minor Issues

* There's a lone visible backslash (`/`) after the name inputs at `/account/profile`
* First Name and Last Name inputs at `/account/profile` should probably just be a single Name or Display Name input

2021-02-04 16:03 UTC, wreality commented
Fixed the email field on the login page.

The /account/profile stuff will get addressed as part of #120

2021-02-04 17:52 UTC, wreality commented
@gmeben just a reminder to mark this approved if you're good with it so I can merge.

2021-02-04 19:21 UTC, gmeben commented
@wreality Sorry, I was busy reviewing #112. I'll spin this up and submit my re-review shortly

2021-02-04 19:32 UTC, gmeben approved these changes

2021-02-04 19:33 UTC, merged