feat(client): update header with pilcrow images
MESH-Research/CCR pull request #1660
Opened 2022-11-30 22:37 UTC by wreality

closes #1659

2022-12-01 21:02 UTC, gmeben requested changes
The favicon successfully appears once I clear my browser's cache.

In Chrome and Safari on macOS, The logo's transparency does not appear and there are a couple leftover line artifacts in its lower-right corner. Is it possible to remove these lines and make it so that the transparency is only around the logo like this?

![before-and-after](https://user-images.githubusercontent.com/2668987/205158473-bbdd1dbd-c767-43f8-8beb-fb6684cf8d46.png)

2022-12-01 21:07 UTC, wreality commented on client/src/components/AppHeader.vue
> +          <small class="site-subtitle">Submission Review System</small>
Since this will eventually be something that the application administrator can change/edit through site settings, I don't think it should be in i18n.

2022-12-01 21:08 UTC, wreality commented on client/src/components/AppHeader.vue
> +          alt="Pilcrow logo"
I was going to say that the logo will eventually be changeable by the application admins, but I'll just change it to "logo" and add it to i18n.

2022-12-02 01:50 UTC, gmeben approved these changes
The resolution of the logo is a bit too small that it appears pixelated on a retina display, but I'll say it's good enough for now. 

![pixelated](https://user-images.githubusercontent.com/2668987/205196483-10f5a206-ff83-4b91-885c-ba8be41857d3.png)

2022-12-02 17:31 UTC, merged