feat: Changing font size
MESH-Research/CCR pull request #1689
Opened 2022-12-09 21:07 UTC by vilagshe

Closes #1035 

- Adds functionality Font Increase and Decrease buttons
- Adds jest testing

2022-12-09 21:29 UTC, gmeben requested changes
Oh, I forgot that the intended scope of #1035 involves changing the font in addition to changing the font size, so we'll need to make the font dropdown functional as well. The specification was not very clear on this and that's on me, so I apologize. 

It's probably safe to consider the Quasar default font as the 'sans-serif' font. I tried to see if a serif font has ever been specified for this by anybody and I wasn't able to find anything. It's probably best to try some options and consult the team on this before we make a final decision for the serif font.

2022-12-09 21:31 UTC, vilagshe commented
> 

I thought we decided on Georgia for the serif font? That's what is in the style guide.

2022-12-10 00:16 UTC, gmeben commented
Ah, that's right. We'll go with Georgia.

2022-12-13 21:12 UTC, gmeben approved these changes

2022-12-13 21:20 UTC, merged