feat: Initial design of the manage submissions page.
MESH-Research/CCR pull request #458
Opened 2021-07-26 19:30 UTC by Sruthin86

Review Checklist
 - [ ] Create a new view for the Submissions page.
 - [ ] Add a h3 for the dropdown.
 - [ ] Add and h3 for reviewers section
 - [ ] Create a dropdown to demonstrate the addition of reviewers to a submission.
 - [ ] Create a list to display the added reviewers.
 - [ ] Add a user avatar in the list.
 - [ ] Add email address under the display name.

2021-07-26 21:10 UTC, gmeben requested changes

2021-07-26 21:10 UTC, gmeben commented on client/src/pages/SubmissionDetails.vue
> +              hint="Minimum 2 characters to trigger filtering"
Screen Reader for Chrome (ChromeVox) only announces the hint when this element is tabbed, which means Screen Reader should read something that more clearly describes its purpose.
```suggestion
              hint="Search for a user to assign."
```

2021-07-26 21:12 UTC, gmeben commented
It occurred to me that this is missing a Jest and Cypress test.

2021-07-29 19:39 UTC, Sruthin86 reviewed
Grant, I looked at your changes and approved them. Do you have to approve the review so that this can be merged into development and master?

2021-07-30 17:23 UTC, gmeben commented
@Sruthin86 Yes, it has to be approved by another user before it's eligible to be merged. I didn't approve it because the Cypress and Jest tests were still missing. I've added them, so now I can go through your review checklist.

2021-07-30 19:45 UTC, merged