refactor(client): factor out repeated makeNotify functions
MESH-Research/CCR pull request #939
Opened 2022-03-11 21:53 UTC by wreality

Closes #828

2022-03-11 21:57 UTC, wreality commented on client/src/use/guiElements.js
> +      timeout: 50000,
```suggestion
      timeout: 5000,
```

2022-03-12 02:01 UTC, gmeben requested changes
Excellent work

2022-03-12 06:32 UTC, wreality commented on client/src/use/guiElements.js
> +          label: "Close",
Yep. It was copy and pasted where it wasn't translated. I'll update.

2022-03-12 18:24 UTC, gmeben approved these changes

2022-03-13 18:51 UTC, merged